[project]
name = "umip"
version = "0.0.0"
description = "Universal MIP"
authors = [{ name = "Matthias Als", email = "mata@ecco.com" }]
maintainers = [{ name = "ECCO Data & AI", email = "esdsupport@ecco.com"}]
requires-python = ">=3.11"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy>=2.0.2,<3",
    "scipy>=1.9.0,<2",
    "numexpr==2.11.0",
    "adapta>=4.0,<5",
    "dataclasses-json>=0.6.7,<0.7",
]

[project.optional-dependencies]
ortools = ["ortools>=9.15,<9.16"]
gurobi = ["gurobipy"]
localsolver = ["localsolver>=11.5.20221123,<12"]
highs = ["highspy~=1.14.0"]
docplex = ["docplex>=2.25,<3"]
pyscipopt = ["pyscipopt>=5.4.1,<6"]

[dependency-groups]
dev = [
    "pytest>=9",
    "pytest-cov>=7",
    "pandas>=2.2.0,<3",
    "ruff>=0.16.5",
]

[tool.uv]
default-groups = "all"

[[tool.uv.index]]
name = "localsolver"
url = "https://pip.localsolver.com/"

[tool.ruff]
src = ["src"]
target-version = "py311"
line-length = 120
extend-exclude = ['tests/data/.*']

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = """
    --cov-config=.coveragerc
    --doctest-modules
    --junitxml=junit/test-results.xml
    --cov=.
    --cov-report=term-missing:skip-covered
"""

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
