[tool.poetry]
name = "generic-mip"
version = "0.0.0"
description = "Generic MIP framework"
authors = ["Matthias Als <mata@ecco.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
ortools = "9.3.10497"
gurobipy = "9.5.2"
pandas = "~1.4.3"
numpy = "~1.22.3"
scipy = "~1.9.0"
proteus = "~1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "~6.2.0"
pylint = "~2.14.0"
pytest-cov = "~2.12.1"

[[tool.poetry.source]]
name = "azops"
url = "https://pkgs.dev.azure.com/eccoSneaksAndData/_packaging/eccoSneaksAndData/pypi/simple/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
