name: Release
run-name: Publish ${{github.ref_name}} by @${{ github.actor }}

on: workflow_dispatch

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: SneaksAndData/github-actions/semver_release@v0.1.12
        with:
          major_v: 1
          minor_v: 0
