name: Release
run-name: Publish ${{github.ref_name}} by @${{ github.actor }}

on:
  push:
    branches: [ main ]

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: SneaksAndData/github-actions/semver_release@v0.1.2
        with:
          major_v: 0
          minor_v: 8
  release_to_aws_ca:
    name: Release distribution to AWS CA

    permissions:
      contents: read
      id-token: write
      pull-requests: write
    
    runs-on: ubuntu-latest
    needs: [ create_release ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          architecture: 'x64'
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.2
        with:
          url: https://hashicorp-vault.production.sneaksanddata.com/
          role: github
          method: jwt
          secrets: |
            /secret/data/common/package-publishing/aws-ca/production/artifact-user access_key ;
            /secret/data/common/package-publishing/aws-ca/production/artifact-user access_key_id ;
      - name: Setup AWS CA
        uses: SneaksAndData/github-actions/setup_aws_ca@v0.1.2
        with:
          aws_access_key: ${{ env.ACCESS_KEY }}
          aws_access_key_id: ${{ env.ACCESS_KEY_ID }}
          mode: publish
          aws_ca_domain: esd-code-artifact-production
          aws_ca_domain_owner: 497010676583
          aws_ca_repository: esd-artifacts
        id: setup_aws_ca
      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.1.0
        with:
          pypi_repo_url: ${{ steps.setup_aws_ca.outputs.url }}
          pypi_token_username: ${{ steps.setup_aws_ca.outputs.user }}
          pypi_token: ${{ steps.setup_aws_ca.outputs.token }}
      - name: Build Package and Publish distribution 📦 to AWS CA
        env:
          POETRY_HTTP_BASIC_CUSTOM_REPO_USERNAME: ${{ steps.setup_aws_ca.outputs.user }}
          POETRY_HTTP_BASIC_CUSTOM_REPO_PASSWORD: ${{ steps.setup_aws_ca.outputs.token }}
        run: |
          set -e
      
          version=$(git describe --tags --abbrev=7)
          sed -i "s/version = \"0.0.0\"/version = \"${version:1}\"/" pyproject.toml
          sed -i "s/__version__ = '0.0.0'/__version__ = \"${version:1}\"/" generic_mip/_version.py
      
          poetry build && poetry publish -r custom_repo
